config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get "/auth/:provider/callback", to: "sessions#create"
  get "/signout", to: "sessions#destroy", as: :signout

  resources :repositories, only: :index do
    collection do
      get 'search'
    end
    resources :repository_tags, only: :create
  end
  resources :repository_tags, only: :destroy

  get "api_doc", to: "pages#api_doc", as: :api_doc

  namespace :api, defaults: { format: :json } do
    get "/starred_by/:username",
        to: "repositories#index",
        as: :index
    post "/apply_tag/:repository_id",
        to: "repository_tags#create",
        as: :apply_tag
    get "/search_by_tag/:tag_name",
        to: "repositories#search",
        as: :search
    get "/recommend_tags/:repository_id",
        to: "repository_tags#recommend",
        as: :recommend_tag
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  has_many :repository_users, dependent: :destroy
  has_many :users, through: :repository_users
  has_many :repository_tags, dependent: :destroy
  has_many :tags, through: :repository_tags

  before_validation { self.language = "undefined" if self.language.nil? }

  %i[github_id name html_url language].each do |attr|
    validates attr, presence: true
  end

  validates :github_id, uniqueness: true, numericality: { only_integer: true }

  default_scope { includes(:tags) }
end

app/models/repository_tag.rb
# frozen_string_literal: true

class RepositoryTag < ApplicationRecord
  belongs_to :repository
  belongs_to :tag
  belongs_to :user

  delegate :name, to: :tag

  validates :tag, uniqueness: { scope: [:repository, :user] }
  validate :user_has_repository

  private

    def user_has_repository
      unless user.repositories.include? repository
        errors.add(:tag, "cannot be placed on someone else's repository")
      end
    end
end

app/models/repository_user.rb
# frozen_string_literal: true

class RepositoryUser < ApplicationRecord
  belongs_to :repository
  belongs_to :user

  validates :user, uniqueness: { scope: :repository }
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :repository_tags, dependent: :destroy
  has_many :repositories, through: :repository_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repository_users, dependent: :destroy
  has_many :repositories, through: :repository_users
  has_many :repository_tags, dependent: :destroy

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.username = auth["info"]["nickname"]
    end
  end
end

app/controllers/api/base_controller.rb
# frozen_string_literal: true

class Api::BaseController < ActionController::API
  rescue_from StandardError, with: :internal_server_error
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

    def internal_server_error(exception)
      if Rails.env.development?
        response = { type: exception.class.to_s, message: exception.message, backtrace: exception.backtrace }
      else
        response = { error: "Internal Server Error" }
      end
      render json: response, status: :internal_server_error
    end

    def not_found(exception)
      render json: { error: exception.message }, status: :not_found
    end
end

app/controllers/api/repositories_controller.rb
# frozen_string_literal: true

class Api::RepositoriesController < Api::BaseController
  def index
    [Repository, RepositoryTag].each { |klass| klass.destroy_all }
    @username = helpers.sanitize(params[:username]).strip
    @repos = ReposFetcher.fetch(@username)
    @repos.each { |repo| repo[:language] ||= "undefined" }
  end

  def search
    @search_tag = params.permit(:tag_name)[:tag_name]
    @repos = Search.api(@search_tag)
  end
end

app/controllers/api/repository_tags_controller.rb
# frozen_string_literal: true

class Api::RepositoryTagsController < Api::BaseController
  before_action :set_repository

  def create
    name = permitted_params[:tag_name]
    tag = Tag.find_by(name: name) || Tag.create(name: name)
    RepositoryTag.create(repository: @repo, tag: tag)
    response
      .set_header("Location", "repositories/#{permitted_params[:repository_id]}")
    render :create, status: :created
  end

  def recommend
    @repo = Repository.find_by(github_id: params[:repository_id])
    @recommendations = [@repo.language.downcase]
    @recommendations = ["documentation"] if @recommendations == ["undefined"]
  end

  private

    def set_repository
      @repo =
        Repository
        .find_by(github_id: permitted_params[:repository_id])
    end

    def permitted_params
      params.permit(:repository_id, :tag_name)
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :searched_user

  private

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def searched_user
      User.find_by(username: session[:username]) || current_user
    end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
  end

  def api_doc
    render layout: false
  end
end

app/controllers/repositories_controller.rb
# frozen_string_literal: true

class RepositoriesController < ApplicationController
  before_action :set_user

  def index
    repos = ReposFetcher.fetch(session[:username])
    @repos = recommend(repos)
  end

  def search
    @search_tag = params.permit(:tag_name)[:tag_name]
    repos = Search.browser(@search_tag, @searched_user)
    repos = @searched_user.repositories if @search_tag.empty?
    @repos = recommend(repos)
    render "repositories/index"
  end

  private

    def set_user
      session[:username] = helpers
                            .sanitize(params[:username])
                            .strip if params[:username]
      @searched_user = searched_user
    end

    def recommend(repos)
      repos_with_recommendations = repos.map do |repo|
        { record: repo, recommendation: Recommendation.get(repo, searched_user) }
      end
      repos_with_recommendations
    end
end

app/controllers/repository_tags_controller.rb
# frozen_string_literal: true

class RepositoryTagsController < ApplicationController
  def create
    @repo_tag = RepositoryTag.create(repository_id: params[:repository_id],
                                     tag: set_tag,
                                     user: searched_user)
    @repo = Repository.find(params[:repository_id])
    @recommendation = Recommendation.get(@repo, searched_user)
  end

  def destroy
    @id = params[:id]
    RepositoryTag.find(@id).destroy
  end

  private

    def set_tag
      Tag.find_by(name: params.permit(:name)[:name]) || Tag.create(params.permit(:name))
    end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def owner?
    return false if current_user.nil?
    session[:username] == current_user.username
  end

  def message(repos, search_tag)
    if @repos.empty? && @search_tag && owner?
      :empty_search_own
    elsif @repos.empty? && owner?
      :no_own_starred_repos
    elsif owner?
      :found_own_repos
    elsif @repos.empty? && @search_tag
      :empty_search
    elsif @repos.empty?
      :no_starred_repos
    else
      :found_repos
    end
  end

  def tags(repo, user)
    repo.repository_tags.select { |repo_tag| repo_tag.user == user }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Githubstars</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div id="main-wrapper">
      <%= yield %>
    </div>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div id="main-form">
  <%= form_tag "/repositories", method: "get" do %>
    <%= label_tag "username", "https://github.com/" %>
    <%= text_field_tag "username", nil, placeholder: "username" %>
    <%= submit_tag "get repositories", id: "submit" %>
  <% end %>
</div>

app/views/pages/repos.html.erb
<%= "Oops, no starred repositories were found." if @repos.empty? %>

<% @repos.each do |repo| %>
  <p><%= link_to repo[:name], repo[:html_url] %> |
     <%= repo[:description] %> |
     <%= repo[:language] || "undefined" %></p>
<% end %>

app/views/repositories/_filler.html.erb
<% rows.times do %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <% if owner? %>
      <td></td>
    <% end %>
  </tr>
<% end %>

app/views/repositories/_message.html.erb
<p>
  <% case message(repos, search_tag) %>
  <% when :empty_search_own %>
  Welcome, <strong><%= session[:username] %></strong>! You have no repositories with tags matching <strong><%= search_tag %></strong>.
  <% when :no_own_starred_repos %>
  Welcome, <strong><%= session[:username] %></strong>! You have no starred repositories so far.
  <% when :found_own_repos %>
  Welcome, <strong><%= session[:username] %></strong>! Here are your starred repositories.
  <% when :empty_search %>
  Oops, no starred repositories with tags matching <strong><%= search_tag %></strong> were found for user <strong><%= session[:username] %></strong>.
  <% when :no_starred_repos %>
  Oops, no starred repositories were found for user <strong><%= session[:username] %></strong>.
  <% when :found_repos %>
  <strong><%= session[:username] %></strong>'s starred repositories
  <% end %>
</p>

app/views/repositories/_repo_data.html.erb
<td><%= link_to repo.name, repo.html_url %></td>
<td class="description"><%= repo.description %></td>
<td><%= repo.language.downcase || "undefined" %></td>
<td class="tags">
  <% tags(repo, @searched_user).each do |repo_tag| %>
    <div id="repo-tag<%= repo_tag.id %>">
      <%= repo_tag.name %>&nbsp;<%= link_to "x", repo_tag, method: :delete, remote: true %>
    </div>
  <% end %>
</td>

app/views/repositories/_repo_row.html.erb
<tr id="repo-<%= repo[:record].id %>">
  <%= render "repo_data", repo: repo[:record] %>
  <%= render "tag_input", repo: repo if owner? %>
</tr>

app/views/repositories/_search.html.erb
<%= form_tag search_repositories_path, method: :get do %>
  <%= text_field_tag :tag_name, nil, placeholder: @search_tag %>
  <%= submit_tag "search" %>
<% end %>

app/views/repositories/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Repository</th>
      <th class="description">Description</th>
      <th>Language</th>
      <th class="tags">Tags</th>
      <% if owner? %>
        <th>Add tag</th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% repos.each do |repo| %>
      <%= render "repo_row", repo: repo %>
    <% end %>
    <%# Fill out the page with empty lines if needed (wireframe)  %>
    <%= render "filler", rows: (13 - repos.length) %>
  </tbody>
</table>

app/views/repositories/_tag_input.html.erb
<td>
  <%= form_for [repo[:record], RepositoryTag.new], remote: true do |f| %>
    <%= text_field_tag :name, repo[:recommendation], class: "tag-input tag-input-gray" %>
    <%= submit_tag "+", class: "tag-submit" %>
  <% end %>
</td>

app/views/repositories/index.html.erb
<div id="table-container">
  <header id="main-label">
    <%= render "search" %>
    <%= render "message", repos: @repos, search_tag: @search_tag %>
  </header>
  <%= render "table", repos: @repos %>
</div>

app/views/repository_tags/create.js.erb
document
  .querySelector('#repo-<%= @repo.id %> > .tags')
  .innerHTML +=
    '<div id="repo-tag<%= @repo_tag.id %>">\
      <%= @repo_tag.name %>&nbsp;<%= link_to "x", repository_tag_path(@repo_tag), method: :delete, remote: true %>\
    </div>'
document.querySelector('#repo-<%= @repo.id %> input[name="name"]').value = '<%= @recommendation %>';

app/views/repository_tags/destroy.js.erb
document.getElementById('repo-tag<%= @id %>').remove();

app/views/shared/_navbar.html.erb
<div id="navbar">
  <h2>githubstars</h2>
  <div id="navbar-right">
    <% if current_user %>
      <strong><%= current_user.username %></strong>
      <small><%= link_to "Sign out", signout_path %></small>
    <% else %>
      <%= link_to "Sign in", "/auth/github" %> with GitHub
    <% end %>
     - - <%= link_to "API docs 🇧🇷", api_doc_path %> - -
    <%= link_to "home", root_path %>
  </div>
</div>